this.addDependency("Private Island Command" , "Private Island")
this.addDependency("Private Island Aliases", "Private Island")
this.addDependency("Hub Command" , "Hub")
this.addDependency("Hub Aliases", "Hub")
this.addDependency("Community Center Aliases", "Community Center")
this.addDependency("Castle Ruins Aliases", "Castle Ruins")
this.addDependency("Sirius Shack Aliases", "Sirius Shack")
this.addDependency("Hub Crypts Command" , "Hub Crypts")
this.addDependency("Hub Crypts Aliases", "Hub Crypts")
this.addDependency("Museum Aliases", "Museum")
this.addDependency("Dungeon Hub Command" , "Dungeon Hub")
this.addDependency("Dungeon Hub Aliases", "Dungeon Hub")
this.addDependency("The Barn Aliases", "The Barn")
this.addDependency("Mushroom Desert Aliases", "Mushroom Desert")
this.addDependency("Trapper's Den Command" , "Trapper's Den")
this.addDependency("Trapper's Den Aliases", "Trapper's Den")
this.addDependency("The Park Aliases", "The Park")
this.addDependency("Jungle Aliases", "Jungle")
this.addDependency("Howling Cave Aliases", "Howling Cave")
this.addDependency("Gold Mine Aliases", "Gold Mine")
this.addDependency("Deep Caverns Aliases", "Deep Caverns")
this.addDependency("Dwarven Mines Aliases", "Dwarven Mines")
this.addDependency("The Forge Aliases", "The Forge")
this.addDependency("Crystal Hollows Command" , "Crystal Hollows")
this.addDependency("Crystal Hollows Aliases", "Crystal Hollows")
this.addDependency("Crystal Nucleus Aliases", "Crystal Nucleus")
this.addDependency("Spider's Den Command" , "Spider's Den")
this.addDependency("Spider's Den Aliases", "Spider's Den")
this.addDependency("Spider Mound Command" , "Spider Mound")
this.addDependency("Spider Mound Aliases", "Spider Mound")
this.addDependency("Arachne's Sanctuary Aliases", "Arachne's Sanctuary")
this.addDependency("The End Aliases", "The End")
this.addDependency("Dragon's Nest Aliases", "Dragon's Nest")
this.addDependency("Void Sepulture Command" , "Void Sepulture")
this.addDependency("Void Sepulture Aliases", "Void Sepulture")
this.addDependency("Crimson Isle Command" , "Crimson Isle")
this.addDependency("Crimson Isle Aliases", "Crimson Isle")
this.addDependency("Forgotten Skull Aliases", "Forgotten Skull")
this.addDependency("The Wasteland Aliases", "The Wasteland")
this.addDependency("Dragontail Aliases", "Dragontail")
this.addDependency("Scarleton Aliases", "Scarleton")
this.addDependency("Smolderimg Tomb Command" , "Smolderimg Tomb")
this.addDependency("Smolderimg Tomb Aliases", "Smolderimg Tomb")
this.addDependency("Garden Aliases", "Garden")
this.addDependency("Jerry's Workshop Command" , "Jerry's Workshop")
this.addDependency("Jerry's Workshop Aliases", "Jerry's Workshop")