export interface Config {

enabled: boolean;
name: string;

private_island: boolean
private_island_selector: number
private_island_aliases: string
hub: boolean
hub_selector: number
hub_aliases: string
community_center: boolean
community_center_aliases: string
castle_ruins: boolean
castle_ruins_aliases: string
sirius_shack: boolean
sirius_shack_aliases: string
hub_crypts: boolean
hub_crypts_selector: number
hub_crypts_aliases: string
museum: boolean
museum_aliases: string
dungeon_hub: boolean
dungeon_hub_selector: number
dungeon_hub_aliases: string
the_barn: boolean
the_barn_aliases: string
mushroom_desert: boolean
mushroom_desert_aliases: string
trappers_den: boolean
trappers_den_selector: number
trappers_den_aliases: string
the_park: boolean
the_park_aliases: string
jungle: boolean
jungle_aliases: string
howling_cave: boolean
howling_cave_aliases: string
gold_mine: boolean
gold_mine_aliases: string
deep_caverns: boolean
deep_caverns_aliases: string
dwarven_mines: boolean
dwarven_mines_aliases: string
the_forge: boolean
the_forge_aliases: string
crystal_hollows: boolean
crystal_hollows_selector: number
crystal_hollows_aliases: string
crystal_nucleus: boolean
crystal_nucleus_aliases: string
spiders_den: boolean
spiders_den_selector: number
spiders_den_aliases: string
spider_mound: boolean
spider_mound_selector: number
spider_mound_aliases: string
arachnes_sanctuary: boolean
arachnes_sanctuary_aliases: string
the_end: boolean
the_end_aliases: string
dragons_nest: boolean
dragons_nest_aliases: string
void_sepulture: boolean
void_sepulture_selector: number
void_sepulture_aliases: string
crimson_isle: boolean
crimson_isle_selector: number
crimson_isle_aliases: string
forgotten_skull: boolean
forgotten_skull_aliases: string
the_wasteland: boolean
the_wasteland_aliases: string
dragontail: boolean
dragontail_aliases: string
scarleton: boolean
scarleton_aliases: string
smolderimg_tomb: boolean
smolderimg_tomb_selector: number
smolderimg_tomb_aliases: string
garden: boolean
garden_aliases: string
jerrys_workshop: boolean
jerrys_workshop_selector: number
jerrys_workshop_aliases: string
}